### ISSUE TITLE
Value needs to be changed before validation passes when autoform type is method

### ISSUE THREAD

**Issue by sonyl** [muqube/meteor-autoform-nouislider#1]
Otherwise optional: false validation will fail.

This is simply a copy from an unresolved Issue in the https://github.com/ElevateDev/meteor-autoform-nouislider project.
As mentioned by the original issue author, a simple fix, that worked for me, was to remove
https://github.com/muqube/meteor-autoform-nouislider/blob/master/autoform-nouislider.js#L7

**Comment by raiyankamal** [comment]
Hi, thanks for reporting the issue. Will fix this soon.
