### ISSUE TITLE
Do you need a maintainer?

### ISSUE THREAD

**Issue by jankapunkt** [muqube/meteor-autoform-nouislider#11]
I could maintain this repo as I will continue to use Blaze for a while. Are you interested?

**Comment by raiyankamal** [comment]
Hi Jan,
that's a great suggestion. I've not used meteor in years and did not have time or reason to work on this repo for a long time. Do you want me to transfer the ownership to this account: @jankapunkt ? Let me know.

**Comment by jankapunkt** [comment]
That would be great! Yes the account is @jankapunkt Thanks a lot for the love to the community I will o my best in taking care.

**Comment by raiyankamal** [comment]
Hey, looks like github wouldn't allow to directly transfer the ownership to you because the repo is owned by an org. How about I add you to the org and give you privilege to admin the repo?

**Comment by jankapunkt** [comment]
That's also fine. However I will try to publish in order to see if there
are any issues regarding the atmosphere account.

Edit: removed sensitive information that has been added by answering via email

**Comment by jankapunkt** [comment]
Could you please add me in the meantime to the org?

**Comment by raiyankamal** [comment]
Hi Jan,
I added you to the org as a member. Github showed me two privilege levels: member and owner. I made you a member for now. If this does not work out, I can make you a owner. Please let me know how it goes.

**Comment by jankapunkt** [comment]
Thank you I will check on it today and let you know when I have trouble with something.

**Comment by jankapunkt** [comment]
Hey I just found two issues regarding permissions.

The first problem is, that I can't push to the repo. I get the following error on push:

```
ERROR: Permission to muqube/meteor-autoform-nouislider.git denied to jankapunkt.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Can you please check the permission I have regarding the rep?

The second problem is, that I can't publish to atmosphere. I also did not find any option to add maintainers to the atmosphere package. However, I opened a [question in the forum](https://forums.meteor.com/t/adding-maintainers-to-atmosphere-package/46588) about that, so maybe it is possible to add maintainers.

If it is not possible to add maintainers on atmosphere, I would suggest the following:

* keep developing the package on github within this org and repo
* keep all versions <=0.4.0 as they are on atmosphere
* continue publishing on atmosphere by using my account for all versions >0.4.0

What do you think?

**Comment by raiyankamal** [comment]
Looks like the default permission for org members was set to 'read', I have set that to 'write' now. Please check if you can push to the repo now.

I'll try if I can add you as a maintainer, or somehow transfer ownership of the atmosphere. Will get back to you shortly.

**Comment by raiyankamal** [comment]
Hi Jan,
I saw that meteor.com has organization. But I'm not sure if that helps us in case of publishing in atmosphere. I'll be still on the look out for that. If you happen to come across that feature, let me know.
In case we cannot find it, I'll be happy to do the publishing. It's a pretty low effort task to be honest. I just don't have the time to add new features and test them before making releases. As long as someone collaborates with me to take care of that part, I'll be fine.

**Comment by jankapunkt** [comment]
@raiyankamal Thanks a lot, I just pushed to a new branch called 0.5 and the workflow you proposed sounds great.
I will continue to work on the package and let you know when there is a release ready when I merge the branch into `master`.
