### ISSUE TITLE
Remove underscore dependency

### ISSUE THREAD

**Issue by jankapunkt** [muqube/meteor-autoform-nouislider#15]
I have completely freed my projects from underscore and the only package, that depends on it is this one.

Would it make sense to replace the `_.pick` and `_.omit` calls with custom functions so we can be independent from underscore?

**Comment by raiyankamal** [comment]
Hi @jankapunkt I'd be happy to review if you can send a PR for this.

**Comment by jankapunkt** [comment]
I will implement this immediately after #16 is merged, since #16 also fixes compatibility issues with autoform and simpl-schema

**Comment by raiyankamal** [comment]
Hi @jankapunkt thanks for sending the PRs, reviewing.

**Comment by raiyankamal** [comment]
#16 and #17 both are merged. We should be ready for another release now. What do you think?
