### ISSUE TITLE
sliders.value output are only integer, could it be float ?

### ISSUE THREAD

**Issue by steven-tib** [muqube/meteor-autoform-nouislider#4]
Hi, 

I'm working with sliders having small lower and upper values, something ranging between 0 and 2 of 0.05 and 0.08 sometimes. The results is that I need to output float values. However, it seems that this integration of noUISlider is only outputing integer, could it be because of the `first` and `second` variables parsed as integer ? Could we change it in `parseFloat` or would it mess the rest of the code ? or could we add an option to allow outputting float values ?

```
AutoForm.addInputType("noUiSlider", {
  template: "afNoUiSlider",
  valueOut: function(){
    var slider = this.find('.nouislider');

    if( this.attr("data-type") === "Object" ){
      var first = parseInt(slider.val()[0]);
      var second = parseInt(slider.val()[1]);
      var value = {
        lower: first > second ? second : first,
        upper: first > second ? first : second
      };
      return value;
    }else{
      return slider.val();
    }
  }
});
```

Maybe my issue caused by something else, any idea ? 

I'm trying to test it on my side but I don't have any experience with modifying packages, I thought it would be quicker to ask here.

_Note: I have set the concerned values in the schema as `decimal:true`_ 

thanks for your help

**Comment by raiyankamal** [comment]
Hi @steven-tib,
this seems could be an enhancement on top of the existing feature. I'll examine the code and get back to you soon. Thanks.

**Comment by steven-tib** [comment]
Thank you @raiyankamal ! I'm looking forward to getting your update about this.

**Comment by raiyankamal** [comment]
You're welcome :)

I played around with the package a bit to find out the current state of things. For a single slider value it worked out of the box. I tried with the below field definition in my schema.

```
decimalSlider: {
    type: Number,
    max: 5,
    min: 0,
    decimal: true,
    autoform: {
        type: "noUiSlider",
        noUiSliderOptions: {
            step: 0.25
        },
        noUiSlider_pipsOptions: {
            mode: 'steps',
            density: 5
        }
    }
},
```

For range sliders though, things didn't work out of the box. So we need to edit the code where values are being parsed. 

For both single slider and range slider, the pips are seen as rounded numbers. This should be also corrected.

Let me know if I'm missing something.

**Comment by steven-tib** [comment]
Hi, 
thanks for investigating. 

For the pips being seen as rounded number, we can change this by adding the format options as below : 

```
 rangeDecimalSlider: {
    type: RangeSchema,
    decimal: true,
    label: 'label_text',
    min: 0.05,
    max: 0.0801, //workaround, fixes bug which not display the max value label if 0.08. May be linked with filter option
    optional: true,
    autoform: {
      type: "noUiSlider",
      noUiSliderOptions: {
        step: 0.005
      },      
      noUiSlider_pipsOptions: {
        mode: 'steps',
        density: 2,
        filter: 2
        format: wNumb({
          decimals: 3
        })
      }
    }
  },
```

(needs wNumb to be added, package: rudolfs:wnumb
see also [http://refreshless.com/nouislider/pips/#section-steps](http://refreshless.com/nouislider/pips/#section-steps))

Note: I also have some other issues but I will open new tickets for those ones (see workaround with 0.0801 max value) and another with tooltips (not displaying) and filter option. But one thing at a time :)

**Comment by raiyankamal** [comment]
Hi @steven-tib,
feel free to add issues as you discover them. I'll work on them whenever I get some time.

I got some time to have a closer look at the pips today. It seems the `format` option would work as is, I tested with this definition below and it worked out for me. Note the format code here is copied from the [nouislider website](http://refreshless.com/nouislider/slider-read-write/#section-formatting).

```
...
singleDecimalSlider: {
    type: Number,
    max: 5,
    min: 0,
    decimal: true,
    autoform: {
        type: "noUiSlider",
        noUiSliderOptions: {
            step: 0.25
        },
        noUiSlider_pipsOptions: {
            mode: 'steps',
            density: 5,
            format: {
                to: function ( value ) {
                    return value;
                },
                from: function ( value ) {
                    return value;
                }
            }
        }
    }
},
...
```

Since things are looking ok so far, I'll merge the working branch and make a release soon.
