### ISSUE TITLE
update dependency to autoform 6.0.0

### ISSUE THREAD

**Issue by abate** [muqube/meteor-autoform-nouislider#9]
Thanks !

**Comment by raiyankamal** [comment]
Hi @abate, I'll be happy to accept some contribution on this issue. I'm currently unable to allocate time to work on this project. If you already have a solution, feel free to send me a pull request. Cheers.

**Comment by abate** [comment]
I've tested this package with the new autoform locally. You just need to add aldeed:autoform@6.0.0 as the package dependency and make a new release . that's all. I can prepare a PR, but I guess it will take less time to just do it yourself.

**Comment by jankapunkt** [comment]
@abate and all who still are interested in this package - there will be an update within the upcoming week to the latest noUISlider version and AutoForm versions. Backwardcompatibility still needs to be tested.

**Comment by raiyankamal** [comment]
Happy new year to all!

**Comment by raiyankamal** [comment]
@jankapunkt let me know when you are ready for a release. Or if you have any roadblocks that I might be able to resolve. Thanks.

**Comment by jankapunkt** [comment]
@raiyankamal I tested with my app the version bump and there were no problems. I would merge the 0.5 branch with master so you could publish the up-to-date version.

Edit: Happy new year 👍

**Comment by jankapunkt** [comment]
Please see #12

**Comment by raiyankamal** [comment]
@jankapunkt your PR is merged. I made another branch `0.4.1` to update the docs a little bit and also for keeping a separate release branch for that version just in case. Have a look at the PR: https://github.com/muqube/meteor-autoform-nouislider/pull/14
We can move ahead with the release once this one is merged.
